# Generated by Django 5.1.3 on 2024-11-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_aucs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendario',
            name='imagem',
            field=models.CharField(default='aa', max_length=100),
            preserve_default=False,
        ),
    ]
