# Generated by Django 5.1.3 on 2024-11-14 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('arquivo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Letra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra0', models.CharField(blank=True, max_length=60, null=True)),
                ('letra1', models.CharField(blank=True, max_length=60, null=True)),
                ('letra2', models.CharField(blank=True, max_length=60, null=True)),
                ('letra3', models.CharField(blank=True, max_length=60, null=True)),
                ('letra4', models.CharField(blank=True, max_length=60, null=True)),
                ('letra5', models.CharField(blank=True, max_length=60, null=True)),
                ('letra6', models.CharField(blank=True, max_length=60, null=True)),
                ('letra7', models.CharField(blank=True, max_length=60, null=True)),
                ('letra8', models.CharField(blank=True, max_length=60, null=True)),
                ('letra9', models.CharField(blank=True, max_length=60, null=True)),
                ('ponto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pontos.ponto')),
            ],
        ),
    ]
