# Generated by Django 5.1.3 on 2024-11-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto',
            name='linha',
            field=models.CharField(default='aa', max_length=30),
            preserve_default=False,
        ),
    ]
